[sdl]
fullscreen=false
autolock=true

[dosbox]
machine=svga_s3
memsize=16

[render]
aspect=true
scaler=normal2x

[cpu]
core=normal
cputype=386_slow
cycles=12000
cycleup=500
cycledown=500

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=25

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[autoexec]
@echo off
mount c .
c:
CORNCOB.BAT
